version: '3.9'

networks:
  default:

services:
  database:
    image: postgres:alpine
    restart: always
    networks:
      - default
    environment:
      - POSRGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=resilia_workshop_backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    expose:
      - "5436"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    networks:
      - default
    env_file: .env
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
      - 9001:9001
    depends_on:
      database:
        condition: service_healthy

volumes:
  db-data: